name: publish
on:
  push:
    tags:
      - '*.*.*.*'
jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Download Dalamud Latest
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Zip Plugin
      run: Compress-Archive -Path .\build\* -DestinationPath .\build\EasyZoomReborn.zip
    - name: Publish Plugin
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/EasyZoomReborn.zip
        token: ${{ secrets.GITHUB_TOKEN }}
